// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/node/llm/addModelsInfos": {
            "post": {
                "description": "添加模型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node/llm"
                ],
                "summary": "添加模型信息",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.AddModelsInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/llm/addModelsProvider": {
            "post": {
                "description": "添加模型供应商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NodeLLM"
                ],
                "summary": "添加模型供应商",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.AddModelsProviderInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/llm/billingUsage": {
            "post": {
                "description": "节点计费上报",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "节点计费上报",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.NodeReportUsageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/llm/listNodeInfos": {
            "post": {
                "description": "获取模型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "获取模型信息",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.ListNodeInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/llm/mapModelsProviderInfoToNode": {
            "post": {
                "description": "映射模型和模型供应商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NodeLLM"
                ],
                "summary": "映射模型和模型供应商",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.MapModelsProviderInfoToNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/llm/nodeUnRegister": {
            "post": {
                "description": "LLM节点用户注销",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM模型节点管理"
                ],
                "summary": "LLM节点用户注销",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "节点用户ID",
                        "name": "nodeUserId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "节点用户注销请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.NodeUnRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/llm/upsetNodeInfos": {
            "post": {
                "description": "添加/更新节点信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "添加/更新节点信息",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpsetNodeInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/public/login": {
            "post": {
                "description": "登录用户",
                "summary": "登录用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.LoginUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/user/checkUserBalance": {
            "post": {
                "description": "节点查询用户余额接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点管理"
                ],
                "summary": "节点查询用户余额接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点ID",
                        "name": "nodeId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UserBalanceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.UserBalanceResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/user/getUserInfo": {
            "post": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetUserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/user/listUsers": {
            "post": {
                "description": "用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "description": "用户列表",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.ListUsersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ListUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/user/logout": {
            "post": {
                "description": "用户登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.LogoutUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/node/user/updateUserInfo": {
            "post": {
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateUserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.UpdateUserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/users/system/nodeUserActive": {
            "get": {
                "description": "激活节点用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Node"
                ],
                "summary": "激活节点用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点用户ID",
                        "name": "nodeUserId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "节点用户激活码",
                        "name": "nodeUserActiveCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/users/system/register": {
            "post": {
                "description": "注册节点用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Node"
                ],
                "summary": "注册节点用户",
                "parameters": [
                    {
                        "description": "注册节点用户请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.DefaultResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "requests.AddModelsInfoRequest": {
            "type": "object",
            "properties": {
                "models_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/requests.ModelsInfo"
                    }
                }
            }
        },
        "requests.AddModelsProviderInfoRequest": {
            "type": "object",
            "properties": {
                "models_provider_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/requests.ModelsProviderInfo"
                    }
                }
            }
        },
        "requests.ListNodeInfoRequest": {
            "type": "object",
            "properties": {
                "node_user_id": {
                    "type": "integer"
                },
                "page_info": {
                    "$ref": "#/definitions/requests.PageReq"
                }
            }
        },
        "requests.ListUsersRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "page": {
                    "$ref": "#/definitions/requests.PageReq"
                },
                "status": {
                    "description": "0:全部 1:正常 2:禁用",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "requests.MapModelsProviderInfoToNodeRequest": {
            "type": "object",
            "required": [
                "model_id",
                "node_id",
                "provider_ids"
            ],
            "properties": {
                "model_id": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "integer"
                },
                "provider_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "requests.ModelsInfo": {
            "type": "object",
            "required": [
                "api_version",
                "deploy_name",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "api_version": {
                    "type": "string"
                },
                "cache_price": {
                    "type": "integer"
                },
                "deploy_name": {
                    "type": "string"
                },
                "input_price": {
                    "type": "integer"
                },
                "is_private": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "output_price": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "requests.ModelsProviderInfo": {
            "type": "object",
            "required": [
                "endpoint",
                "name",
                "type"
            ],
            "properties": {
                "api_keys": {
                    "type": "string"
                },
                "api_type": {
                    "type": "string"
                },
                "cache_price": {
                    "type": "integer"
                },
                "endpoint": {
                    "type": "string"
                },
                "input_price": {
                    "type": "integer"
                },
                "model_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "output_price": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "requests.NodeReportUsageReq": {
            "type": "object",
            "required": [
                "node_id"
            ],
            "properties": {
                "node_id": {
                    "type": "string"
                },
                "report": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/requests.UsageReport"
                    }
                }
            }
        },
        "requests.NodeUnRegisterReq": {
            "type": "object",
            "required": [
                "mail",
                "name"
            ],
            "properties": {
                "mail": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "requests.PageReq": {
            "type": "object",
            "required": [
                "limit",
                "skip"
            ],
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "skip": {
                    "type": "integer"
                },
                "sort": {
                    "type": "string"
                }
            }
        },
        "requests.RegisterUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 6
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 11
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "requests.TokenUsage": {
            "type": "object",
            "properties": {
                "cached_tokens": {
                    "type": "integer"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "latency": {
                    "type": "number"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "reasoning_tokens": {
                    "type": "integer"
                },
                "tokens_per_sec": {
                    "type": "integer"
                }
            }
        },
        "requests.UpdateUserInfoRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 50
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 11
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "requests.UpsetNodeInfoRequest": {
            "type": "object",
            "properties": {
                "access_key": {
                    "type": "string"
                },
                "company_id": {
                    "type": "integer"
                },
                "domain": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_user_id": {
                    "type": "integer"
                },
                "secret_key": {
                    "type": "string"
                }
            }
        },
        "requests.UsageReport": {
            "type": "object",
            "properties": {
                "actual_model": {
                    "description": "实际使用的模型",
                    "type": "string"
                },
                "actual_provider": {
                    "description": "实际服务商",
                    "type": "string"
                },
                "actual_provider_id": {
                    "description": "实际服务商id",
                    "type": "string"
                },
                "agent_version": {
                    "type": "string"
                },
                "caller": {
                    "type": "string"
                },
                "caller_key": {
                    "type": "string"
                },
                "client_version": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_private": {
                    "description": "是否私有模型",
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "model_id": {
                    "description": "模型id（计费使用）",
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "token_usage": {
                    "$ref": "#/definitions/requests.TokenUsage"
                }
            }
        },
        "requests.UserBalanceReq": {
            "type": "object",
            "required": [
                "user_id",
                "wallet_type"
            ],
            "properties": {
                "user_id": {
                    "type": "integer"
                },
                "wallet_type": {
                    "type": "string"
                }
            }
        },
        "responses.DefaultResponse": {
            "type": "object"
        },
        "responses.GetUserInfoResponse": {
            "type": "object",
            "properties": {
                "user_info": {
                    "$ref": "#/definitions/responses.UserInfoResponse"
                }
            }
        },
        "responses.ListUsersResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.UserInfoResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "responses.LoginUserResponse": {
            "type": "object",
            "properties": {
                "expire_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_info": {
                    "$ref": "#/definitions/responses.UserInfoResponse"
                }
            }
        },
        "responses.LogoutUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "responses.UpdateUserInfoResponse": {
            "type": "object",
            "properties": {
                "user_info": {
                    "$ref": "#/definitions/responses.UserInfoResponse"
                }
            }
        },
        "responses.UserBalanceResp": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "wallet_address": {
                    "type": "string"
                },
                "wallet_type": {
                    "type": "string"
                }
            }
        },
        "responses.UserInfoResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "description": "1:正常 2:禁用",
                    "type": "integer"
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "TopModelsLogin Backend Service",
	Description:      "This is the backend services for TopModelsLogin, providing user management and LLM",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
